// prisma.config.ts
import "dotenv/config";
import { defineConfig, env } from "prisma/config"; // ← import from "prisma/config", not "@prisma/config"

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: env("DATABASE_URL"), // ← use DATABASE_URL which is defined in env/local configs
  },
});



// // This file was generated by Prisma, and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//     seed: "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts",  
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });
